services:
  - type: web
    name: strapi
    runtime: node
    plan: starter
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    disk:
      name: strapi-uploads
      mountPath: /opt/render/project/src/public/uploads
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: 12.22.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: softqr-api
          property: postgresql://softqr-api_owner:ulvXqkw4B6gd@ep-twilight-voice-a2b1e2sp.eu-central-1.aws.neon.tech/softqr-api?sslmode=require
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true

databases:
  - name: softqr-api
    plan: starter